// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_new_media.proto

package ru.spice.at.common.dto.dam.grpc;

public final class EventNewMedia {
  private EventNewMedia() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MediaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.spice.at.common.dto.dam.grpc.Media)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 external_offer_id = 1;</code>
     * @return The externalOfferId.
     */
    long getExternalOfferId();

    /**
     * <code>uint64 master_seller_id = 2;</code>
     * @return The masterSellerId.
     */
    long getMasterSellerId();

    /**
     * <code>string metadata_id = 3;</code>
     * @return The metadataId.
     */
    String getMetadataId();
    /**
     * <code>string metadata_id = 3;</code>
     * @return The bytes for metadataId.
     */
    com.google.protobuf.ByteString
        getMetadataIdBytes();

    /**
     * <code>string url = 4;</code>
     * @return The url.
     */
    String getUrl();
    /**
     * <code>string url = 4;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
     * @return Whether the priority field is set.
     */
    boolean hasPriority();
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
     * @return The priority.
     */
    NullableInt32 getPriority();
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
     */
    NullableInt32OrBuilder getPriorityOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp updated_at = 6;</code>
     * @return Whether the updatedAt field is set.
     */
    boolean hasUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 6;</code>
     * @return The updatedAt.
     */
    com.google.protobuf.Timestamp getUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();
  }
  /**
   * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.Media}
   */
  public  static final class Media extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.spice.at.common.dto.dam.grpc.Media)
      MediaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Media.newBuilder() to construct.
    private Media(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Media() {
      metadataId_ = "";
      url_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Media();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Media(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              externalOfferId_ = input.readUInt64();
              break;
            }
            case 16: {

              masterSellerId_ = input.readUInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              metadataId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 42: {
              NullableInt32.Builder subBuilder = null;
              if (priority_ != null) {
                subBuilder = priority_.toBuilder();
              }
              priority_ = input.readMessage(NullableInt32.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(priority_);
                priority_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (updatedAt_ != null) {
                subBuilder = updatedAt_.toBuilder();
              }
              updatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(updatedAt_);
                updatedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventNewMedia.internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventNewMedia.internal_static_ru_spice_at_common_dto_dam_grpc_Media_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Media.class, Builder.class);
    }

    public static final int EXTERNAL_OFFER_ID_FIELD_NUMBER = 1;
    private long externalOfferId_;
    /**
     * <code>uint64 external_offer_id = 1;</code>
     * @return The externalOfferId.
     */
    public long getExternalOfferId() {
      return externalOfferId_;
    }

    public static final int MASTER_SELLER_ID_FIELD_NUMBER = 2;
    private long masterSellerId_;
    /**
     * <code>uint64 master_seller_id = 2;</code>
     * @return The masterSellerId.
     */
    public long getMasterSellerId() {
      return masterSellerId_;
    }

    public static final int METADATA_ID_FIELD_NUMBER = 3;
    private volatile Object metadataId_;
    /**
     * <code>string metadata_id = 3;</code>
     * @return The metadataId.
     */
    public String getMetadataId() {
      Object ref = metadataId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        metadataId_ = s;
        return s;
      }
    }
    /**
     * <code>string metadata_id = 3;</code>
     * @return The bytes for metadataId.
     */
    public com.google.protobuf.ByteString
        getMetadataIdBytes() {
      Object ref = metadataId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        metadataId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 4;
    private volatile Object url_;
    /**
     * <code>string url = 4;</code>
     * @return The url.
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 4;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIORITY_FIELD_NUMBER = 5;
    private NullableInt32 priority_;
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
     * @return Whether the priority field is set.
     */
    public boolean hasPriority() {
      return priority_ != null;
    }
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
     * @return The priority.
     */
    public NullableInt32 getPriority() {
      return priority_ == null ? NullableInt32.getDefaultInstance() : priority_;
    }
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
     */
    public NullableInt32OrBuilder getPriorityOrBuilder() {
      return getPriority();
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp updatedAt_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 6;</code>
     * @return Whether the updatedAt field is set.
     */
    public boolean hasUpdatedAt() {
      return updatedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 6;</code>
     * @return The updatedAt.
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      return getUpdatedAt();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (externalOfferId_ != 0L) {
        output.writeUInt64(1, externalOfferId_);
      }
      if (masterSellerId_ != 0L) {
        output.writeUInt64(2, masterSellerId_);
      }
      if (!getMetadataIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, metadataId_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, url_);
      }
      if (priority_ != null) {
        output.writeMessage(5, getPriority());
      }
      if (updatedAt_ != null) {
        output.writeMessage(6, getUpdatedAt());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (externalOfferId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, externalOfferId_);
      }
      if (masterSellerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, masterSellerId_);
      }
      if (!getMetadataIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, metadataId_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, url_);
      }
      if (priority_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPriority());
      }
      if (updatedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getUpdatedAt());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Media)) {
        return super.equals(obj);
      }
      Media other = (Media) obj;

      if (getExternalOfferId()
          != other.getExternalOfferId()) return false;
      if (getMasterSellerId()
          != other.getMasterSellerId()) return false;
      if (!getMetadataId()
          .equals(other.getMetadataId())) return false;
      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (hasPriority() != other.hasPriority()) return false;
      if (hasPriority()) {
        if (!getPriority()
            .equals(other.getPriority())) return false;
      }
      if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
      if (hasUpdatedAt()) {
        if (!getUpdatedAt()
            .equals(other.getUpdatedAt())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXTERNAL_OFFER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExternalOfferId());
      hash = (37 * hash) + MASTER_SELLER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMasterSellerId());
      hash = (37 * hash) + METADATA_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataId().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      if (hasPriority()) {
        hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
        hash = (53 * hash) + getPriority().hashCode();
      }
      if (hasUpdatedAt()) {
        hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatedAt().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Media parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Media parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Media parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Media parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Media parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Media parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Media parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Media parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Media parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Media parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Media parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Media parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Media prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.Media}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.spice.at.common.dto.dam.grpc.Media)
        MediaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EventNewMedia.internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EventNewMedia.internal_static_ru_spice_at_common_dto_dam_grpc_Media_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Media.class, Builder.class);
      }

      // Construct using ru.spice.at.common.dto.dam.grpc.EventNewMedia.Media.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        externalOfferId_ = 0L;

        masterSellerId_ = 0L;

        metadataId_ = "";

        url_ = "";

        if (priorityBuilder_ == null) {
          priority_ = null;
        } else {
          priority_ = null;
          priorityBuilder_ = null;
        }
        if (updatedAtBuilder_ == null) {
          updatedAt_ = null;
        } else {
          updatedAt_ = null;
          updatedAtBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EventNewMedia.internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor;
      }

      @Override
      public Media getDefaultInstanceForType() {
        return Media.getDefaultInstance();
      }

      @Override
      public Media build() {
        Media result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Media buildPartial() {
        Media result = new Media(this);
        result.externalOfferId_ = externalOfferId_;
        result.masterSellerId_ = masterSellerId_;
        result.metadataId_ = metadataId_;
        result.url_ = url_;
        if (priorityBuilder_ == null) {
          result.priority_ = priority_;
        } else {
          result.priority_ = priorityBuilder_.build();
        }
        if (updatedAtBuilder_ == null) {
          result.updatedAt_ = updatedAt_;
        } else {
          result.updatedAt_ = updatedAtBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Media) {
          return mergeFrom((Media)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Media other) {
        if (other == Media.getDefaultInstance()) return this;
        if (other.getExternalOfferId() != 0L) {
          setExternalOfferId(other.getExternalOfferId());
        }
        if (other.getMasterSellerId() != 0L) {
          setMasterSellerId(other.getMasterSellerId());
        }
        if (!other.getMetadataId().isEmpty()) {
          metadataId_ = other.metadataId_;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.hasPriority()) {
          mergePriority(other.getPriority());
        }
        if (other.hasUpdatedAt()) {
          mergeUpdatedAt(other.getUpdatedAt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Media parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Media) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long externalOfferId_ ;
      /**
       * <code>uint64 external_offer_id = 1;</code>
       * @return The externalOfferId.
       */
      public long getExternalOfferId() {
        return externalOfferId_;
      }
      /**
       * <code>uint64 external_offer_id = 1;</code>
       * @param value The externalOfferId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalOfferId(long value) {
        
        externalOfferId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 external_offer_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalOfferId() {
        
        externalOfferId_ = 0L;
        onChanged();
        return this;
      }

      private long masterSellerId_ ;
      /**
       * <code>uint64 master_seller_id = 2;</code>
       * @return The masterSellerId.
       */
      public long getMasterSellerId() {
        return masterSellerId_;
      }
      /**
       * <code>uint64 master_seller_id = 2;</code>
       * @param value The masterSellerId to set.
       * @return This builder for chaining.
       */
      public Builder setMasterSellerId(long value) {
        
        masterSellerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 master_seller_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMasterSellerId() {
        
        masterSellerId_ = 0L;
        onChanged();
        return this;
      }

      private Object metadataId_ = "";
      /**
       * <code>string metadata_id = 3;</code>
       * @return The metadataId.
       */
      public String getMetadataId() {
        Object ref = metadataId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          metadataId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string metadata_id = 3;</code>
       * @return The bytes for metadataId.
       */
      public com.google.protobuf.ByteString
          getMetadataIdBytes() {
        Object ref = metadataId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          metadataId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string metadata_id = 3;</code>
       * @param value The metadataId to set.
       * @return This builder for chaining.
       */
      public Builder setMetadataId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        metadataId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string metadata_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMetadataId() {
        
        metadataId_ = getDefaultInstance().getMetadataId();
        onChanged();
        return this;
      }
      /**
       * <code>string metadata_id = 3;</code>
       * @param value The bytes for metadataId to set.
       * @return This builder for chaining.
       */
      public Builder setMetadataIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        metadataId_ = value;
        onChanged();
        return this;
      }

      private Object url_ = "";
      /**
       * <code>string url = 4;</code>
       * @return The url.
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string url = 4;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 4;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 4;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private NullableInt32 priority_;
      private com.google.protobuf.SingleFieldBuilderV3<
          NullableInt32, NullableInt32.Builder, NullableInt32OrBuilder> priorityBuilder_;
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
       * @return Whether the priority field is set.
       */
      public boolean hasPriority() {
        return priorityBuilder_ != null || priority_ != null;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
       * @return The priority.
       */
      public NullableInt32 getPriority() {
        if (priorityBuilder_ == null) {
          return priority_ == null ? NullableInt32.getDefaultInstance() : priority_;
        } else {
          return priorityBuilder_.getMessage();
        }
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
       */
      public Builder setPriority(NullableInt32 value) {
        if (priorityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          priority_ = value;
          onChanged();
        } else {
          priorityBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
       */
      public Builder setPriority(
          NullableInt32.Builder builderForValue) {
        if (priorityBuilder_ == null) {
          priority_ = builderForValue.build();
          onChanged();
        } else {
          priorityBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
       */
      public Builder mergePriority(NullableInt32 value) {
        if (priorityBuilder_ == null) {
          if (priority_ != null) {
            priority_ =
              NullableInt32.newBuilder(priority_).mergeFrom(value).buildPartial();
          } else {
            priority_ = value;
          }
          onChanged();
        } else {
          priorityBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
       */
      public Builder clearPriority() {
        if (priorityBuilder_ == null) {
          priority_ = null;
          onChanged();
        } else {
          priority_ = null;
          priorityBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
       */
      public NullableInt32.Builder getPriorityBuilder() {
        
        onChanged();
        return getPriorityFieldBuilder().getBuilder();
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
       */
      public NullableInt32OrBuilder getPriorityOrBuilder() {
        if (priorityBuilder_ != null) {
          return priorityBuilder_.getMessageOrBuilder();
        } else {
          return priority_ == null ?
              NullableInt32.getDefaultInstance() : priority_;
        }
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt32 priority = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          NullableInt32, NullableInt32.Builder, NullableInt32OrBuilder>
          getPriorityFieldBuilder() {
        if (priorityBuilder_ == null) {
          priorityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              NullableInt32, NullableInt32.Builder, NullableInt32OrBuilder>(
                  getPriority(),
                  getParentForChildren(),
                  isClean());
          priority_ = null;
        }
        return priorityBuilder_;
      }

      private com.google.protobuf.Timestamp updatedAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp updated_at = 6;</code>
       * @return Whether the updatedAt field is set.
       */
      public boolean hasUpdatedAt() {
        return updatedAtBuilder_ != null || updatedAt_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 6;</code>
       * @return The updatedAt.
       */
      public com.google.protobuf.Timestamp getUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        } else {
          return updatedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 6;</code>
       */
      public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updatedAt_ = value;
          onChanged();
        } else {
          updatedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 6;</code>
       */
      public Builder setUpdatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = builderForValue.build();
          onChanged();
        } else {
          updatedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 6;</code>
       */
      public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (updatedAt_ != null) {
            updatedAt_ =
              com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
          } else {
            updatedAt_ = value;
          }
          onChanged();
        } else {
          updatedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 6;</code>
       */
      public Builder clearUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = null;
          onChanged();
        } else {
          updatedAt_ = null;
          updatedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
        
        onChanged();
        return getUpdatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
        if (updatedAtBuilder_ != null) {
          return updatedAtBuilder_.getMessageOrBuilder();
        } else {
          return updatedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getUpdatedAtFieldBuilder() {
        if (updatedAtBuilder_ == null) {
          updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getUpdatedAt(),
                  getParentForChildren(),
                  isClean());
          updatedAt_ = null;
        }
        return updatedAtBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.spice.at.common.dto.dam.grpc.Media)
    }

    // @@protoc_insertion_point(class_scope:ru.spice.at.common.dto.dam.grpc.Media)
    private static final Media DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Media();
    }

    public static Media getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Media>
        PARSER = new com.google.protobuf.AbstractParser<Media>() {
      @Override
      public Media parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Media(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Media> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Media> getParserForType() {
      return PARSER;
    }

    @Override
    public Media getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NullableInt32OrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.spice.at.common.dto.dam.grpc.NullableInt32)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return The enum numeric value on the wire for null.
     */
    int getNullValue();
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return The null.
     */
    com.google.protobuf.NullValue getNull();

    /**
     * <code>int32 data = 2;</code>
     * @return The data.
     */
    int getData();

    public NullableInt32.KindCase getKindCase();
  }
  /**
   * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.NullableInt32}
   */
  public  static final class NullableInt32 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.spice.at.common.dto.dam.grpc.NullableInt32)
      NullableInt32OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NullableInt32.newBuilder() to construct.
    private NullableInt32(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NullableInt32() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new NullableInt32();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NullableInt32(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
              kindCase_ = 1;
              kind_ = rawValue;
              break;
            }
            case 16: {
              kindCase_ = 2;
              kind_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventNewMedia.internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt32_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventNewMedia.internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt32_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NullableInt32.class, Builder.class);
    }

    private int kindCase_ = 0;
    private Object kind_;
    public enum KindCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      NULL(1),
      DATA(2),
      KIND_NOT_SET(0);
      private final int value;
      private KindCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static KindCase valueOf(int value) {
        return forNumber(value);
      }

      public static KindCase forNumber(int value) {
        switch (value) {
          case 1: return NULL;
          case 2: return DATA;
          case 0: return KIND_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public KindCase
    getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public static final int NULL_FIELD_NUMBER = 1;
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return The enum numeric value on the wire for null.
     */
    public int getNullValue() {
      if (kindCase_ == 1) {
        return (Integer) kind_;
      }
      return 0;
    }
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return The null.
     */
    public com.google.protobuf.NullValue getNull() {
      if (kindCase_ == 1) {
        @SuppressWarnings("deprecation")
        com.google.protobuf.NullValue result = com.google.protobuf.NullValue.valueOf(
            (Integer) kind_);
        return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
      }
      return com.google.protobuf.NullValue.NULL_VALUE;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    /**
     * <code>int32 data = 2;</code>
     * @return The data.
     */
    public int getData() {
      if (kindCase_ == 2) {
        return (Integer) kind_;
      }
      return 0;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (kindCase_ == 1) {
        output.writeEnum(1, ((Integer) kind_));
      }
      if (kindCase_ == 2) {
        output.writeInt32(
            2, (int)((Integer) kind_));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (kindCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, ((Integer) kind_));
      }
      if (kindCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              2, (int)((Integer) kind_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NullableInt32)) {
        return super.equals(obj);
      }
      NullableInt32 other = (NullableInt32) obj;

      if (!getKindCase().equals(other.getKindCase())) return false;
      switch (kindCase_) {
        case 1:
          if (getNullValue()
              != other.getNullValue()) return false;
          break;
        case 2:
          if (getData()
              != other.getData()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (kindCase_) {
        case 1:
          hash = (37 * hash) + NULL_FIELD_NUMBER;
          hash = (53 * hash) + getNullValue();
          break;
        case 2:
          hash = (37 * hash) + DATA_FIELD_NUMBER;
          hash = (53 * hash) + getData();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NullableInt32 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NullableInt32 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NullableInt32 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NullableInt32 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NullableInt32 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NullableInt32 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NullableInt32 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NullableInt32 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NullableInt32 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NullableInt32 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NullableInt32 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NullableInt32 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NullableInt32 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.NullableInt32}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.spice.at.common.dto.dam.grpc.NullableInt32)
        NullableInt32OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EventNewMedia.internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt32_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EventNewMedia.internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt32_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NullableInt32.class, Builder.class);
      }

      // Construct using ru.spice.at.common.dto.dam.grpc.EventNewMedia.NullableInt32.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        kindCase_ = 0;
        kind_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EventNewMedia.internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt32_descriptor;
      }

      @Override
      public NullableInt32 getDefaultInstanceForType() {
        return NullableInt32.getDefaultInstance();
      }

      @Override
      public NullableInt32 build() {
        NullableInt32 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NullableInt32 buildPartial() {
        NullableInt32 result = new NullableInt32(this);
        if (kindCase_ == 1) {
          result.kind_ = kind_;
        }
        if (kindCase_ == 2) {
          result.kind_ = kind_;
        }
        result.kindCase_ = kindCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NullableInt32) {
          return mergeFrom((NullableInt32)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NullableInt32 other) {
        if (other == NullableInt32.getDefaultInstance()) return this;
        switch (other.getKindCase()) {
          case NULL: {
            setNullValue(other.getNullValue());
            break;
          }
          case DATA: {
            setData(other.getData());
            break;
          }
          case KIND_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NullableInt32 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NullableInt32) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int kindCase_ = 0;
      private Object kind_;
      public KindCase
          getKindCase() {
        return KindCase.forNumber(
            kindCase_);
      }

      public Builder clearKind() {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>.google.protobuf.NullValue null = 1;</code>
       * @return The enum numeric value on the wire for null.
       */
      public int getNullValue() {
        if (kindCase_ == 1) {
          return ((Integer) kind_).intValue();
        }
        return 0;
      }
      /**
       * <code>.google.protobuf.NullValue null = 1;</code>
       * @param value The enum numeric value on the wire for null to set.
       * @return This builder for chaining.
       */
      public Builder setNullValue(int value) {
        kindCase_ = 1;
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.NullValue null = 1;</code>
       * @return The null.
       */
      public com.google.protobuf.NullValue getNull() {
        if (kindCase_ == 1) {
          @SuppressWarnings("deprecation")
          com.google.protobuf.NullValue result = com.google.protobuf.NullValue.valueOf(
              (Integer) kind_);
          return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
        }
        return com.google.protobuf.NullValue.NULL_VALUE;
      }
      /**
       * <code>.google.protobuf.NullValue null = 1;</code>
       * @param value The null to set.
       * @return This builder for chaining.
       */
      public Builder setNull(com.google.protobuf.NullValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        kindCase_ = 1;
        kind_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.NullValue null = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNull() {
        if (kindCase_ == 1) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>int32 data = 2;</code>
       * @return The data.
       */
      public int getData() {
        if (kindCase_ == 2) {
          return (Integer) kind_;
        }
        return 0;
      }
      /**
       * <code>int32 data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(int value) {
        kindCase_ = 2;
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.spice.at.common.dto.dam.grpc.NullableInt32)
    }

    // @@protoc_insertion_point(class_scope:ru.spice.at.common.dto.dam.grpc.NullableInt32)
    private static final NullableInt32 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NullableInt32();
    }

    public static NullableInt32 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NullableInt32>
        PARSER = new com.google.protobuf.AbstractParser<NullableInt32>() {
      @Override
      public NullableInt32 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NullableInt32(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NullableInt32> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NullableInt32> getParserForType() {
      return PARSER;
    }

    @Override
    public NullableInt32 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_spice_at_common_dto_dam_grpc_Media_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt32_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt32_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025event_new_media.proto\022\037ru.spice.at.com" +
      "mon.dto.dam.grpc\032\034google/protobuf/struct" +
      ".proto\032\037google/protobuf/timestamp.proto\"" +
      "\320\001\n\005Media\022\031\n\021external_offer_id\030\001 \001(\004\022\030\n\020" +
      "master_seller_id\030\002 \001(\004\022\023\n\013metadata_id\030\003 " +
      "\001(\t\022\013\n\003url\030\004 \001(\t\022@\n\010priority\030\005 \001(\0132..ru." +
      "spice.at.common.dto.dam.grpc.NullableInt" +
      "32\022.\n\nupdated_at\030\006 \001(\0132\032.google.protobuf" +
      ".Timestamp\"S\n\rNullableInt32\022*\n\004null\030\001 \001(" +
      "\0162\032.google.protobuf.NullValueH\000\022\016\n\004data\030" +
      "\002 \001(\005H\000B\006\n\004kindB\002Z\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_spice_at_common_dto_dam_grpc_Media_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor,
        new String[] { "ExternalOfferId", "MasterSellerId", "MetadataId", "Url", "Priority", "UpdatedAt", });
    internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt32_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt32_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt32_descriptor,
        new String[] { "Null", "Data", "Kind", });
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
