// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: offer_update.proto

package ru.spice.at.common.dto.dam.grpc;

public final class OfferUpdateOuterClass {
  private OfferUpdateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OfferUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.spice.at.common.dto.dam.grpc.OfferUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 external_offer_id = 1;</code>
     * @return The externalOfferId.
     */
    long getExternalOfferId();

    /**
     * <code>uint32 master_seller_id = 2;</code>
     * @return The masterSellerId.
     */
    int getMasterSellerId();

    /**
     * <code>uint32 master_category_id = 3;</code>
     * @return The masterCategoryId.
     */
    int getMasterCategoryId();

    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
     * @return Whether the externalTaskId field is set.
     */
    boolean hasExternalTaskId();
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
     * @return The externalTaskId.
     */
    NullableInt getExternalTaskId();
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
     */
    NullableIntOrBuilder getExternalTaskIdOrBuilder();

    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
     * @return Whether the sku field is set.
     */
    boolean hasSku();
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
     * @return The sku.
     */
    NullableInt getSku();
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
     */
    NullableIntOrBuilder getSkuOrBuilder();

    /**
     * <code>bool is_own_trademark = 6;</code>
     * @return The isOwnTrademark.
     */
    boolean getIsOwnTrademark();

    /**
     * <code>bool draft_done = 7;</code>
     * @return The draftDone.
     */
    boolean getDraftDone();

    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status status = 8;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status status = 8;</code>
     * @return The status.
     */
    OfferUpdate.Status getStatus();

    /**
     * <code>string comment = 9;</code>
     * @return The comment.
     */
    String getComment();
    /**
     * <code>string comment = 9;</code>
     * @return The bytes for comment.
     */
    com.google.protobuf.ByteString
        getCommentBytes();
  }
  /**
   * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.OfferUpdate}
   */
  public  static final class OfferUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.spice.at.common.dto.dam.grpc.OfferUpdate)
      OfferUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OfferUpdate.newBuilder() to construct.
    private OfferUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OfferUpdate() {
      status_ = 0;
      comment_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new OfferUpdate();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OfferUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              externalOfferId_ = input.readInt64();
              break;
            }
            case 16: {

              masterSellerId_ = input.readUInt32();
              break;
            }
            case 24: {

              masterCategoryId_ = input.readUInt32();
              break;
            }
            case 34: {
              NullableInt.Builder subBuilder = null;
              if (externalTaskId_ != null) {
                subBuilder = externalTaskId_.toBuilder();
              }
              externalTaskId_ = input.readMessage(NullableInt.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(externalTaskId_);
                externalTaskId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              NullableInt.Builder subBuilder = null;
              if (sku_ != null) {
                subBuilder = sku_.toBuilder();
              }
              sku_ = input.readMessage(NullableInt.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sku_);
                sku_ = subBuilder.buildPartial();
              }

              break;
            }
            case 48: {

              isOwnTrademark_ = input.readBool();
              break;
            }
            case 56: {

              draftDone_ = input.readBool();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              comment_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OfferUpdateOuterClass.internal_static_ru_spice_at_common_dto_dam_grpc_OfferUpdate_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OfferUpdateOuterClass.internal_static_ru_spice_at_common_dto_dam_grpc_OfferUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OfferUpdate.class, Builder.class);
    }

    /**
     * Protobuf enum {@code ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NOT_TAKEN = 0;</code>
       */
      NOT_TAKEN(0),
      /**
       * <code>BINDED = 1;</code>
       */
      BINDED(1),
      /**
       * <code>IN_WORK_MATCHING = 2;</code>
       */
      IN_WORK_MATCHING(2),
      /**
       * <code>NEED_CREATE_PRODUCT = 3;</code>
       */
      NEED_CREATE_PRODUCT(3),
      /**
       * <code>NEED_CREATE_VARIANT_PRODUCT = 4;</code>
       */
      NEED_CREATE_VARIANT_PRODUCT(4),
      /**
       * <code>NEED_CREATE_CATEGORY = 5;</code>
       */
      NEED_CREATE_CATEGORY(5),
      /**
       * <code>IMPOSSIBLE_TO_PROCESS = 6;</code>
       */
      IMPOSSIBLE_TO_PROCESS(6),
      /**
       * <code>DOUBLE = 7;</code>
       */
      DOUBLE(7),
      /**
       * <code>NOT_REQUIRE_PROCESSING = 8;</code>
       */
      NOT_REQUIRE_PROCESSING(8),
      /**
       * <code>CONTENT_REQUEST_REQUIRED = 9;</code>
       */
      CONTENT_REQUEST_REQUIRED(9),
      /**
       * <code>CONTENT_REQUESTED = 10;</code>
       */
      CONTENT_REQUESTED(10),
      /**
       * <code>UNABLE_TO_REQUEST_CONTENT = 11;</code>
       */
      UNABLE_TO_REQUEST_CONTENT(11),
      /**
       * <code>CONTENT_REQUESTED_NOT_ANSWER = 12;</code>
       */
      CONTENT_REQUESTED_NOT_ANSWER(12),
      /**
       * <code>IN_WORK_CREATE_PRODUCT = 13;</code>
       */
      IN_WORK_CREATE_PRODUCT(13),
      /**
       * <code>IN_WORK_CREATE_CATEGORY = 14;</code>
       */
      IN_WORK_CREATE_CATEGORY(14),
      /**
       * <code>REQUIRED_TO_REQUEST_CONTENT_FROM_RETAILER = 15;</code>
       */
      REQUIRED_TO_REQUEST_CONTENT_FROM_RETAILER(15),
      /**
       * <code>NOT_CURRENT_ASSORTMENT = 17;</code>
       */
      NOT_CURRENT_ASSORTMENT(17),
      /**
       * <code>DRAFT_COMPLETED = 20;</code>
       */
      DRAFT_COMPLETED(20),
      /**
       * <code>OFFER_SWITCH_OFF = 21;</code>
       */
      OFFER_SWITCH_OFF(21),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NOT_TAKEN = 0;</code>
       */
      public static final int NOT_TAKEN_VALUE = 0;
      /**
       * <code>BINDED = 1;</code>
       */
      public static final int BINDED_VALUE = 1;
      /**
       * <code>IN_WORK_MATCHING = 2;</code>
       */
      public static final int IN_WORK_MATCHING_VALUE = 2;
      /**
       * <code>NEED_CREATE_PRODUCT = 3;</code>
       */
      public static final int NEED_CREATE_PRODUCT_VALUE = 3;
      /**
       * <code>NEED_CREATE_VARIANT_PRODUCT = 4;</code>
       */
      public static final int NEED_CREATE_VARIANT_PRODUCT_VALUE = 4;
      /**
       * <code>NEED_CREATE_CATEGORY = 5;</code>
       */
      public static final int NEED_CREATE_CATEGORY_VALUE = 5;
      /**
       * <code>IMPOSSIBLE_TO_PROCESS = 6;</code>
       */
      public static final int IMPOSSIBLE_TO_PROCESS_VALUE = 6;
      /**
       * <code>DOUBLE = 7;</code>
       */
      public static final int DOUBLE_VALUE = 7;
      /**
       * <code>NOT_REQUIRE_PROCESSING = 8;</code>
       */
      public static final int NOT_REQUIRE_PROCESSING_VALUE = 8;
      /**
       * <code>CONTENT_REQUEST_REQUIRED = 9;</code>
       */
      public static final int CONTENT_REQUEST_REQUIRED_VALUE = 9;
      /**
       * <code>CONTENT_REQUESTED = 10;</code>
       */
      public static final int CONTENT_REQUESTED_VALUE = 10;
      /**
       * <code>UNABLE_TO_REQUEST_CONTENT = 11;</code>
       */
      public static final int UNABLE_TO_REQUEST_CONTENT_VALUE = 11;
      /**
       * <code>CONTENT_REQUESTED_NOT_ANSWER = 12;</code>
       */
      public static final int CONTENT_REQUESTED_NOT_ANSWER_VALUE = 12;
      /**
       * <code>IN_WORK_CREATE_PRODUCT = 13;</code>
       */
      public static final int IN_WORK_CREATE_PRODUCT_VALUE = 13;
      /**
       * <code>IN_WORK_CREATE_CATEGORY = 14;</code>
       */
      public static final int IN_WORK_CREATE_CATEGORY_VALUE = 14;
      /**
       * <code>REQUIRED_TO_REQUEST_CONTENT_FROM_RETAILER = 15;</code>
       */
      public static final int REQUIRED_TO_REQUEST_CONTENT_FROM_RETAILER_VALUE = 15;
      /**
       * <code>NOT_CURRENT_ASSORTMENT = 17;</code>
       */
      public static final int NOT_CURRENT_ASSORTMENT_VALUE = 17;
      /**
       * <code>DRAFT_COMPLETED = 20;</code>
       */
      public static final int DRAFT_COMPLETED_VALUE = 20;
      /**
       * <code>OFFER_SWITCH_OFF = 21;</code>
       */
      public static final int OFFER_SWITCH_OFF_VALUE = 21;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return NOT_TAKEN;
          case 1: return BINDED;
          case 2: return IN_WORK_MATCHING;
          case 3: return NEED_CREATE_PRODUCT;
          case 4: return NEED_CREATE_VARIANT_PRODUCT;
          case 5: return NEED_CREATE_CATEGORY;
          case 6: return IMPOSSIBLE_TO_PROCESS;
          case 7: return DOUBLE;
          case 8: return NOT_REQUIRE_PROCESSING;
          case 9: return CONTENT_REQUEST_REQUIRED;
          case 10: return CONTENT_REQUESTED;
          case 11: return UNABLE_TO_REQUEST_CONTENT;
          case 12: return CONTENT_REQUESTED_NOT_ANSWER;
          case 13: return IN_WORK_CREATE_PRODUCT;
          case 14: return IN_WORK_CREATE_CATEGORY;
          case 15: return REQUIRED_TO_REQUEST_CONTENT_FROM_RETAILER;
          case 17: return NOT_CURRENT_ASSORTMENT;
          case 20: return DRAFT_COMPLETED;
          case 21: return OFFER_SWITCH_OFF;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return OfferUpdate.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status)
    }

    public static final int EXTERNAL_OFFER_ID_FIELD_NUMBER = 1;
    private long externalOfferId_;
    /**
     * <code>int64 external_offer_id = 1;</code>
     * @return The externalOfferId.
     */
    public long getExternalOfferId() {
      return externalOfferId_;
    }

    public static final int MASTER_SELLER_ID_FIELD_NUMBER = 2;
    private int masterSellerId_;
    /**
     * <code>uint32 master_seller_id = 2;</code>
     * @return The masterSellerId.
     */
    public int getMasterSellerId() {
      return masterSellerId_;
    }

    public static final int MASTER_CATEGORY_ID_FIELD_NUMBER = 3;
    private int masterCategoryId_;
    /**
     * <code>uint32 master_category_id = 3;</code>
     * @return The masterCategoryId.
     */
    public int getMasterCategoryId() {
      return masterCategoryId_;
    }

    public static final int EXTERNAL_TASK_ID_FIELD_NUMBER = 4;
    private NullableInt externalTaskId_;
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
     * @return Whether the externalTaskId field is set.
     */
    public boolean hasExternalTaskId() {
      return externalTaskId_ != null;
    }
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
     * @return The externalTaskId.
     */
    public NullableInt getExternalTaskId() {
      return externalTaskId_ == null ? NullableInt.getDefaultInstance() : externalTaskId_;
    }
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
     */
    public NullableIntOrBuilder getExternalTaskIdOrBuilder() {
      return getExternalTaskId();
    }

    public static final int SKU_FIELD_NUMBER = 5;
    private NullableInt sku_;
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
     * @return Whether the sku field is set.
     */
    public boolean hasSku() {
      return sku_ != null;
    }
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
     * @return The sku.
     */
    public NullableInt getSku() {
      return sku_ == null ? NullableInt.getDefaultInstance() : sku_;
    }
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
     */
    public NullableIntOrBuilder getSkuOrBuilder() {
      return getSku();
    }

    public static final int IS_OWN_TRADEMARK_FIELD_NUMBER = 6;
    private boolean isOwnTrademark_;
    /**
     * <code>bool is_own_trademark = 6;</code>
     * @return The isOwnTrademark.
     */
    public boolean getIsOwnTrademark() {
      return isOwnTrademark_;
    }

    public static final int DRAFT_DONE_FIELD_NUMBER = 7;
    private boolean draftDone_;
    /**
     * <code>bool draft_done = 7;</code>
     * @return The draftDone.
     */
    public boolean getDraftDone() {
      return draftDone_;
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status status = 8;</code>
     * @return The enum numeric value on the wire for status.
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status status = 8;</code>
     * @return The status.
     */
    public Status getStatus() {
      @SuppressWarnings("deprecation")
      Status result = Status.valueOf(status_);
      return result == null ? Status.UNRECOGNIZED : result;
    }

    public static final int COMMENT_FIELD_NUMBER = 9;
    private volatile Object comment_;
    /**
     * <code>string comment = 9;</code>
     * @return The comment.
     */
    public String getComment() {
      Object ref = comment_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      }
    }
    /**
     * <code>string comment = 9;</code>
     * @return The bytes for comment.
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      Object ref = comment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (externalOfferId_ != 0L) {
        output.writeInt64(1, externalOfferId_);
      }
      if (masterSellerId_ != 0) {
        output.writeUInt32(2, masterSellerId_);
      }
      if (masterCategoryId_ != 0) {
        output.writeUInt32(3, masterCategoryId_);
      }
      if (externalTaskId_ != null) {
        output.writeMessage(4, getExternalTaskId());
      }
      if (sku_ != null) {
        output.writeMessage(5, getSku());
      }
      if (isOwnTrademark_ != false) {
        output.writeBool(6, isOwnTrademark_);
      }
      if (draftDone_ != false) {
        output.writeBool(7, draftDone_);
      }
      if (status_ != Status.NOT_TAKEN.getNumber()) {
        output.writeEnum(8, status_);
      }
      if (!getCommentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, comment_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (externalOfferId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, externalOfferId_);
      }
      if (masterSellerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, masterSellerId_);
      }
      if (masterCategoryId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, masterCategoryId_);
      }
      if (externalTaskId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getExternalTaskId());
      }
      if (sku_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getSku());
      }
      if (isOwnTrademark_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isOwnTrademark_);
      }
      if (draftDone_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, draftDone_);
      }
      if (status_ != Status.NOT_TAKEN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, status_);
      }
      if (!getCommentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, comment_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OfferUpdate)) {
        return super.equals(obj);
      }
      OfferUpdate other = (OfferUpdate) obj;

      if (getExternalOfferId()
          != other.getExternalOfferId()) return false;
      if (getMasterSellerId()
          != other.getMasterSellerId()) return false;
      if (getMasterCategoryId()
          != other.getMasterCategoryId()) return false;
      if (hasExternalTaskId() != other.hasExternalTaskId()) return false;
      if (hasExternalTaskId()) {
        if (!getExternalTaskId()
            .equals(other.getExternalTaskId())) return false;
      }
      if (hasSku() != other.hasSku()) return false;
      if (hasSku()) {
        if (!getSku()
            .equals(other.getSku())) return false;
      }
      if (getIsOwnTrademark()
          != other.getIsOwnTrademark()) return false;
      if (getDraftDone()
          != other.getDraftDone()) return false;
      if (status_ != other.status_) return false;
      if (!getComment()
          .equals(other.getComment())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXTERNAL_OFFER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExternalOfferId());
      hash = (37 * hash) + MASTER_SELLER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMasterSellerId();
      hash = (37 * hash) + MASTER_CATEGORY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMasterCategoryId();
      if (hasExternalTaskId()) {
        hash = (37 * hash) + EXTERNAL_TASK_ID_FIELD_NUMBER;
        hash = (53 * hash) + getExternalTaskId().hashCode();
      }
      if (hasSku()) {
        hash = (37 * hash) + SKU_FIELD_NUMBER;
        hash = (53 * hash) + getSku().hashCode();
      }
      hash = (37 * hash) + IS_OWN_TRADEMARK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOwnTrademark());
      hash = (37 * hash) + DRAFT_DONE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDraftDone());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getComment().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OfferUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OfferUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OfferUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OfferUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OfferUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OfferUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OfferUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OfferUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OfferUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OfferUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OfferUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OfferUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OfferUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.OfferUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.spice.at.common.dto.dam.grpc.OfferUpdate)
        OfferUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OfferUpdateOuterClass.internal_static_ru_spice_at_common_dto_dam_grpc_OfferUpdate_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OfferUpdateOuterClass.internal_static_ru_spice_at_common_dto_dam_grpc_OfferUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OfferUpdate.class, Builder.class);
      }

      // Construct using ru.spice.at.common.dto.dam.grpc.OfferUpdateOuterClass.OfferUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        externalOfferId_ = 0L;

        masterSellerId_ = 0;

        masterCategoryId_ = 0;

        if (externalTaskIdBuilder_ == null) {
          externalTaskId_ = null;
        } else {
          externalTaskId_ = null;
          externalTaskIdBuilder_ = null;
        }
        if (skuBuilder_ == null) {
          sku_ = null;
        } else {
          sku_ = null;
          skuBuilder_ = null;
        }
        isOwnTrademark_ = false;

        draftDone_ = false;

        status_ = 0;

        comment_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OfferUpdateOuterClass.internal_static_ru_spice_at_common_dto_dam_grpc_OfferUpdate_descriptor;
      }

      @Override
      public OfferUpdate getDefaultInstanceForType() {
        return OfferUpdate.getDefaultInstance();
      }

      @Override
      public OfferUpdate build() {
        OfferUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public OfferUpdate buildPartial() {
        OfferUpdate result = new OfferUpdate(this);
        result.externalOfferId_ = externalOfferId_;
        result.masterSellerId_ = masterSellerId_;
        result.masterCategoryId_ = masterCategoryId_;
        if (externalTaskIdBuilder_ == null) {
          result.externalTaskId_ = externalTaskId_;
        } else {
          result.externalTaskId_ = externalTaskIdBuilder_.build();
        }
        if (skuBuilder_ == null) {
          result.sku_ = sku_;
        } else {
          result.sku_ = skuBuilder_.build();
        }
        result.isOwnTrademark_ = isOwnTrademark_;
        result.draftDone_ = draftDone_;
        result.status_ = status_;
        result.comment_ = comment_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OfferUpdate) {
          return mergeFrom((OfferUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OfferUpdate other) {
        if (other == OfferUpdate.getDefaultInstance()) return this;
        if (other.getExternalOfferId() != 0L) {
          setExternalOfferId(other.getExternalOfferId());
        }
        if (other.getMasterSellerId() != 0) {
          setMasterSellerId(other.getMasterSellerId());
        }
        if (other.getMasterCategoryId() != 0) {
          setMasterCategoryId(other.getMasterCategoryId());
        }
        if (other.hasExternalTaskId()) {
          mergeExternalTaskId(other.getExternalTaskId());
        }
        if (other.hasSku()) {
          mergeSku(other.getSku());
        }
        if (other.getIsOwnTrademark() != false) {
          setIsOwnTrademark(other.getIsOwnTrademark());
        }
        if (other.getDraftDone() != false) {
          setDraftDone(other.getDraftDone());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getComment().isEmpty()) {
          comment_ = other.comment_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OfferUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OfferUpdate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long externalOfferId_ ;
      /**
       * <code>int64 external_offer_id = 1;</code>
       * @return The externalOfferId.
       */
      public long getExternalOfferId() {
        return externalOfferId_;
      }
      /**
       * <code>int64 external_offer_id = 1;</code>
       * @param value The externalOfferId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalOfferId(long value) {
        
        externalOfferId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 external_offer_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalOfferId() {
        
        externalOfferId_ = 0L;
        onChanged();
        return this;
      }

      private int masterSellerId_ ;
      /**
       * <code>uint32 master_seller_id = 2;</code>
       * @return The masterSellerId.
       */
      public int getMasterSellerId() {
        return masterSellerId_;
      }
      /**
       * <code>uint32 master_seller_id = 2;</code>
       * @param value The masterSellerId to set.
       * @return This builder for chaining.
       */
      public Builder setMasterSellerId(int value) {
        
        masterSellerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 master_seller_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMasterSellerId() {
        
        masterSellerId_ = 0;
        onChanged();
        return this;
      }

      private int masterCategoryId_ ;
      /**
       * <code>uint32 master_category_id = 3;</code>
       * @return The masterCategoryId.
       */
      public int getMasterCategoryId() {
        return masterCategoryId_;
      }
      /**
       * <code>uint32 master_category_id = 3;</code>
       * @param value The masterCategoryId to set.
       * @return This builder for chaining.
       */
      public Builder setMasterCategoryId(int value) {
        
        masterCategoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 master_category_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMasterCategoryId() {
        
        masterCategoryId_ = 0;
        onChanged();
        return this;
      }

      private NullableInt externalTaskId_;
      private com.google.protobuf.SingleFieldBuilderV3<
          NullableInt, NullableInt.Builder, NullableIntOrBuilder> externalTaskIdBuilder_;
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
       * @return Whether the externalTaskId field is set.
       */
      public boolean hasExternalTaskId() {
        return externalTaskIdBuilder_ != null || externalTaskId_ != null;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
       * @return The externalTaskId.
       */
      public NullableInt getExternalTaskId() {
        if (externalTaskIdBuilder_ == null) {
          return externalTaskId_ == null ? NullableInt.getDefaultInstance() : externalTaskId_;
        } else {
          return externalTaskIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
       */
      public Builder setExternalTaskId(NullableInt value) {
        if (externalTaskIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          externalTaskId_ = value;
          onChanged();
        } else {
          externalTaskIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
       */
      public Builder setExternalTaskId(
          NullableInt.Builder builderForValue) {
        if (externalTaskIdBuilder_ == null) {
          externalTaskId_ = builderForValue.build();
          onChanged();
        } else {
          externalTaskIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
       */
      public Builder mergeExternalTaskId(NullableInt value) {
        if (externalTaskIdBuilder_ == null) {
          if (externalTaskId_ != null) {
            externalTaskId_ =
              NullableInt.newBuilder(externalTaskId_).mergeFrom(value).buildPartial();
          } else {
            externalTaskId_ = value;
          }
          onChanged();
        } else {
          externalTaskIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
       */
      public Builder clearExternalTaskId() {
        if (externalTaskIdBuilder_ == null) {
          externalTaskId_ = null;
          onChanged();
        } else {
          externalTaskId_ = null;
          externalTaskIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
       */
      public NullableInt.Builder getExternalTaskIdBuilder() {
        
        onChanged();
        return getExternalTaskIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
       */
      public NullableIntOrBuilder getExternalTaskIdOrBuilder() {
        if (externalTaskIdBuilder_ != null) {
          return externalTaskIdBuilder_.getMessageOrBuilder();
        } else {
          return externalTaskId_ == null ?
              NullableInt.getDefaultInstance() : externalTaskId_;
        }
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt external_task_id = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          NullableInt, NullableInt.Builder, NullableIntOrBuilder>
          getExternalTaskIdFieldBuilder() {
        if (externalTaskIdBuilder_ == null) {
          externalTaskIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              NullableInt, NullableInt.Builder, NullableIntOrBuilder>(
                  getExternalTaskId(),
                  getParentForChildren(),
                  isClean());
          externalTaskId_ = null;
        }
        return externalTaskIdBuilder_;
      }

      private NullableInt sku_;
      private com.google.protobuf.SingleFieldBuilderV3<
          NullableInt, NullableInt.Builder, NullableIntOrBuilder> skuBuilder_;
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
       * @return Whether the sku field is set.
       */
      public boolean hasSku() {
        return skuBuilder_ != null || sku_ != null;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
       * @return The sku.
       */
      public NullableInt getSku() {
        if (skuBuilder_ == null) {
          return sku_ == null ? NullableInt.getDefaultInstance() : sku_;
        } else {
          return skuBuilder_.getMessage();
        }
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
       */
      public Builder setSku(NullableInt value) {
        if (skuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sku_ = value;
          onChanged();
        } else {
          skuBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
       */
      public Builder setSku(
          NullableInt.Builder builderForValue) {
        if (skuBuilder_ == null) {
          sku_ = builderForValue.build();
          onChanged();
        } else {
          skuBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
       */
      public Builder mergeSku(NullableInt value) {
        if (skuBuilder_ == null) {
          if (sku_ != null) {
            sku_ =
              NullableInt.newBuilder(sku_).mergeFrom(value).buildPartial();
          } else {
            sku_ = value;
          }
          onChanged();
        } else {
          skuBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
       */
      public Builder clearSku() {
        if (skuBuilder_ == null) {
          sku_ = null;
          onChanged();
        } else {
          sku_ = null;
          skuBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
       */
      public NullableInt.Builder getSkuBuilder() {
        
        onChanged();
        return getSkuFieldBuilder().getBuilder();
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
       */
      public NullableIntOrBuilder getSkuOrBuilder() {
        if (skuBuilder_ != null) {
          return skuBuilder_.getMessageOrBuilder();
        } else {
          return sku_ == null ?
              NullableInt.getDefaultInstance() : sku_;
        }
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.NullableInt sku = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          NullableInt, NullableInt.Builder, NullableIntOrBuilder>
          getSkuFieldBuilder() {
        if (skuBuilder_ == null) {
          skuBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              NullableInt, NullableInt.Builder, NullableIntOrBuilder>(
                  getSku(),
                  getParentForChildren(),
                  isClean());
          sku_ = null;
        }
        return skuBuilder_;
      }

      private boolean isOwnTrademark_ ;
      /**
       * <code>bool is_own_trademark = 6;</code>
       * @return The isOwnTrademark.
       */
      public boolean getIsOwnTrademark() {
        return isOwnTrademark_;
      }
      /**
       * <code>bool is_own_trademark = 6;</code>
       * @param value The isOwnTrademark to set.
       * @return This builder for chaining.
       */
      public Builder setIsOwnTrademark(boolean value) {
        
        isOwnTrademark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_own_trademark = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOwnTrademark() {
        
        isOwnTrademark_ = false;
        onChanged();
        return this;
      }

      private boolean draftDone_ ;
      /**
       * <code>bool draft_done = 7;</code>
       * @return The draftDone.
       */
      public boolean getDraftDone() {
        return draftDone_;
      }
      /**
       * <code>bool draft_done = 7;</code>
       * @param value The draftDone to set.
       * @return This builder for chaining.
       */
      public Builder setDraftDone(boolean value) {
        
        draftDone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool draft_done = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDraftDone() {
        
        draftDone_ = false;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status status = 8;</code>
       * @return The enum numeric value on the wire for status.
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status status = 8;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status status = 8;</code>
       * @return The status.
       */
      public Status getStatus() {
        @SuppressWarnings("deprecation")
        Status result = Status.valueOf(status_);
        return result == null ? Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status status = 8;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ru.spice.at.common.dto.dam.grpc.OfferUpdate.Status status = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private Object comment_ = "";
      /**
       * <code>string comment = 9;</code>
       * @return The comment.
       */
      public String getComment() {
        Object ref = comment_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          comment_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string comment = 9;</code>
       * @return The bytes for comment.
       */
      public com.google.protobuf.ByteString
          getCommentBytes() {
        Object ref = comment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          comment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string comment = 9;</code>
       * @param value The comment to set.
       * @return This builder for chaining.
       */
      public Builder setComment(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string comment = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearComment() {
        
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      /**
       * <code>string comment = 9;</code>
       * @param value The bytes for comment to set.
       * @return This builder for chaining.
       */
      public Builder setCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        comment_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.spice.at.common.dto.dam.grpc.OfferUpdate)
    }

    // @@protoc_insertion_point(class_scope:ru.spice.at.common.dto.dam.grpc.OfferUpdate)
    private static final OfferUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OfferUpdate();
    }

    public static OfferUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OfferUpdate>
        PARSER = new com.google.protobuf.AbstractParser<OfferUpdate>() {
      @Override
      public OfferUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OfferUpdate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OfferUpdate> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OfferUpdate> getParserForType() {
      return PARSER;
    }

    @Override
    public OfferUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NullableIntOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.spice.at.common.dto.dam.grpc.NullableInt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return The enum numeric value on the wire for null.
     */
    int getNullValue();
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return The null.
     */
    com.google.protobuf.NullValue getNull();

    /**
     * <code>int32 data = 2;</code>
     * @return The data.
     */
    int getData();

    public NullableInt.KindCase getKindCase();
  }
  /**
   * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.NullableInt}
   */
  public  static final class NullableInt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.spice.at.common.dto.dam.grpc.NullableInt)
      NullableIntOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NullableInt.newBuilder() to construct.
    private NullableInt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NullableInt() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new NullableInt();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NullableInt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
              kindCase_ = 1;
              kind_ = rawValue;
              break;
            }
            case 16: {
              kindCase_ = 2;
              kind_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OfferUpdateOuterClass.internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OfferUpdateOuterClass.internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NullableInt.class, Builder.class);
    }

    private int kindCase_ = 0;
    private Object kind_;
    public enum KindCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      NULL(1),
      DATA(2),
      KIND_NOT_SET(0);
      private final int value;
      private KindCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static KindCase valueOf(int value) {
        return forNumber(value);
      }

      public static KindCase forNumber(int value) {
        switch (value) {
          case 1: return NULL;
          case 2: return DATA;
          case 0: return KIND_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public KindCase
    getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public static final int NULL_FIELD_NUMBER = 1;
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return The enum numeric value on the wire for null.
     */
    public int getNullValue() {
      if (kindCase_ == 1) {
        return (Integer) kind_;
      }
      return 0;
    }
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return The null.
     */
    public com.google.protobuf.NullValue getNull() {
      if (kindCase_ == 1) {
        @SuppressWarnings("deprecation")
        com.google.protobuf.NullValue result = com.google.protobuf.NullValue.valueOf(
            (Integer) kind_);
        return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
      }
      return com.google.protobuf.NullValue.NULL_VALUE;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    /**
     * <code>int32 data = 2;</code>
     * @return The data.
     */
    public int getData() {
      if (kindCase_ == 2) {
        return (Integer) kind_;
      }
      return 0;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (kindCase_ == 1) {
        output.writeEnum(1, ((Integer) kind_));
      }
      if (kindCase_ == 2) {
        output.writeInt32(
            2, (int)((Integer) kind_));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (kindCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, ((Integer) kind_));
      }
      if (kindCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              2, (int)((Integer) kind_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NullableInt)) {
        return super.equals(obj);
      }
      NullableInt other = (NullableInt) obj;

      if (!getKindCase().equals(other.getKindCase())) return false;
      switch (kindCase_) {
        case 1:
          if (getNullValue()
              != other.getNullValue()) return false;
          break;
        case 2:
          if (getData()
              != other.getData()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (kindCase_) {
        case 1:
          hash = (37 * hash) + NULL_FIELD_NUMBER;
          hash = (53 * hash) + getNullValue();
          break;
        case 2:
          hash = (37 * hash) + DATA_FIELD_NUMBER;
          hash = (53 * hash) + getData();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NullableInt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NullableInt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NullableInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NullableInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NullableInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NullableInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NullableInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NullableInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NullableInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NullableInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NullableInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NullableInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NullableInt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.NullableInt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.spice.at.common.dto.dam.grpc.NullableInt)
        NullableIntOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OfferUpdateOuterClass.internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OfferUpdateOuterClass.internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NullableInt.class, Builder.class);
      }

      // Construct using ru.spice.at.common.dto.dam.grpc.OfferUpdateOuterClass.NullableInt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        kindCase_ = 0;
        kind_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OfferUpdateOuterClass.internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt_descriptor;
      }

      @Override
      public NullableInt getDefaultInstanceForType() {
        return NullableInt.getDefaultInstance();
      }

      @Override
      public NullableInt build() {
        NullableInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NullableInt buildPartial() {
        NullableInt result = new NullableInt(this);
        if (kindCase_ == 1) {
          result.kind_ = kind_;
        }
        if (kindCase_ == 2) {
          result.kind_ = kind_;
        }
        result.kindCase_ = kindCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NullableInt) {
          return mergeFrom((NullableInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NullableInt other) {
        if (other == NullableInt.getDefaultInstance()) return this;
        switch (other.getKindCase()) {
          case NULL: {
            setNullValue(other.getNullValue());
            break;
          }
          case DATA: {
            setData(other.getData());
            break;
          }
          case KIND_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NullableInt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NullableInt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int kindCase_ = 0;
      private Object kind_;
      public KindCase
          getKindCase() {
        return KindCase.forNumber(
            kindCase_);
      }

      public Builder clearKind() {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>.google.protobuf.NullValue null = 1;</code>
       * @return The enum numeric value on the wire for null.
       */
      public int getNullValue() {
        if (kindCase_ == 1) {
          return ((Integer) kind_).intValue();
        }
        return 0;
      }
      /**
       * <code>.google.protobuf.NullValue null = 1;</code>
       * @param value The enum numeric value on the wire for null to set.
       * @return This builder for chaining.
       */
      public Builder setNullValue(int value) {
        kindCase_ = 1;
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.NullValue null = 1;</code>
       * @return The null.
       */
      public com.google.protobuf.NullValue getNull() {
        if (kindCase_ == 1) {
          @SuppressWarnings("deprecation")
          com.google.protobuf.NullValue result = com.google.protobuf.NullValue.valueOf(
              (Integer) kind_);
          return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
        }
        return com.google.protobuf.NullValue.NULL_VALUE;
      }
      /**
       * <code>.google.protobuf.NullValue null = 1;</code>
       * @param value The null to set.
       * @return This builder for chaining.
       */
      public Builder setNull(com.google.protobuf.NullValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        kindCase_ = 1;
        kind_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.NullValue null = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNull() {
        if (kindCase_ == 1) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>int32 data = 2;</code>
       * @return The data.
       */
      public int getData() {
        if (kindCase_ == 2) {
          return (Integer) kind_;
        }
        return 0;
      }
      /**
       * <code>int32 data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(int value) {
        kindCase_ = 2;
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.spice.at.common.dto.dam.grpc.NullableInt)
    }

    // @@protoc_insertion_point(class_scope:ru.spice.at.common.dto.dam.grpc.NullableInt)
    private static final NullableInt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NullableInt();
    }

    public static NullableInt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NullableInt>
        PARSER = new com.google.protobuf.AbstractParser<NullableInt>() {
      @Override
      public NullableInt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NullableInt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NullableInt> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NullableInt> getParserForType() {
      return PARSER;
    }

    @Override
    public NullableInt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spice_at_common_dto_dam_grpc_OfferUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_spice_at_common_dto_dam_grpc_OfferUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022offer_update.proto\022\037ru.spice.at.common" +
      ".dto.dam.grpc\032\014struct.proto\"\335\006\n\013OfferUpd" +
      "ate\022\031\n\021external_offer_id\030\001 \001(\003\022\030\n\020master" +
      "_seller_id\030\002 \001(\r\022\032\n\022master_category_id\030\003" +
      " \001(\r\022F\n\020external_task_id\030\004 \001(\0132,.ru.spic" +
      "e.at.common.dto.dam.grpc.NullableInt\0229\n\003" +
      "sku\030\005 \001(\0132,.ru.spice.at.common.dto.dam.g" +
      "rpc.NullableInt\022\030\n\020is_own_trademark\030\006 \001(" +
      "\010\022\022\n\ndraft_done\030\007 \001(\010\022C\n\006status\030\010 \001(\01623." +
      "ru.spice.at.common.dto.dam.grpc.OfferUpd" +
      "ate.Status\022\017\n\007comment\030\t \001(\t\"\365\003\n\006Status\022\r" +
      "\n\tNOT_TAKEN\020\000\022\n\n\006BINDED\020\001\022\024\n\020IN_WORK_MAT" +
      "CHING\020\002\022\027\n\023NEED_CREATE_PRODUCT\020\003\022\037\n\033NEED" +
      "_CREATE_VARIANT_PRODUCT\020\004\022\030\n\024NEED_CREATE" +
      "_CATEGORY\020\005\022\031\n\025IMPOSSIBLE_TO_PROCESS\020\006\022\n" +
      "\n\006DOUBLE\020\007\022\032\n\026NOT_REQUIRE_PROCESSING\020\010\022\034" +
      "\n\030CONTENT_REQUEST_REQUIRED\020\t\022\025\n\021CONTENT_" +
      "REQUESTED\020\n\022\035\n\031UNABLE_TO_REQUEST_CONTENT" +
      "\020\013\022 \n\034CONTENT_REQUESTED_NOT_ANSWER\020\014\022\032\n\026" +
      "IN_WORK_CREATE_PRODUCT\020\r\022\033\n\027IN_WORK_CREA" +
      "TE_CATEGORY\020\016\022-\n)REQUIRED_TO_REQUEST_CON" +
      "TENT_FROM_RETAILER\020\017\022\032\n\026NOT_CURRENT_ASSO" +
      "RTMENT\020\021\022\023\n\017DRAFT_COMPLETED\020\024\022\024\n\020OFFER_S" +
      "WITCH_OFF\020\025\"Q\n\013NullableInt\022*\n\004null\030\001 \001(\016" +
      "2\032.google.protobuf.NullValueH\000\022\016\n\004data\030\002" +
      " \001(\005H\000B\006\n\004kindB\002Z\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_ru_spice_at_common_dto_dam_grpc_OfferUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_spice_at_common_dto_dam_grpc_OfferUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_spice_at_common_dto_dam_grpc_OfferUpdate_descriptor,
        new String[] { "ExternalOfferId", "MasterSellerId", "MasterCategoryId", "ExternalTaskId", "Sku", "IsOwnTrademark", "DraftDone", "Status", "Comment", });
    internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_spice_at_common_dto_dam_grpc_NullableInt_descriptor,
        new String[] { "Null", "Data", "Kind", });
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
