// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product_media_export.proto

package ru.spice.at.common.dto.dam.grpc;

public final class ProductMediaExport {
  private ProductMediaExport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateProductMediaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.spice.at.common.dto.dam.grpc.UpdateProductMedia)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sku = 1;</code>
     * @return The sku.
     */
    String getSku();
    /**
     * <code>string sku = 1;</code>
     * @return The bytes for sku.
     */
    com.google.protobuf.ByteString
        getSkuBytes();

    /**
     * <code>bool full_replacement = 2;</code>
     * @return The fullReplacement.
     */
    boolean getFullReplacement();

    /**
     * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
     */
    java.util.List<Media>
        getMediaList();
    /**
     * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
     */
    Media getMedia(int index);
    /**
     * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
     */
    int getMediaCount();
    /**
     * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
     */
    java.util.List<? extends MediaOrBuilder>
        getMediaOrBuilderList();
    /**
     * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
     */
    MediaOrBuilder getMediaOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.UpdateProductMedia}
   */
  public  static final class UpdateProductMedia extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.spice.at.common.dto.dam.grpc.UpdateProductMedia)
      UpdateProductMediaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateProductMedia.newBuilder() to construct.
    private UpdateProductMedia(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateProductMedia() {
      sku_ = "";
      media_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UpdateProductMedia();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateProductMedia(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              sku_ = s;
              break;
            }
            case 16: {

              fullReplacement_ = input.readBool();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                media_ = new java.util.ArrayList<Media>();
                mutable_bitField0_ |= 0x00000001;
              }
              media_.add(
                  input.readMessage(Media.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          media_ = java.util.Collections.unmodifiableList(media_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductMediaExport.internal_static_ru_spice_at_common_dto_dam_grpc_UpdateProductMedia_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductMediaExport.internal_static_ru_spice_at_common_dto_dam_grpc_UpdateProductMedia_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UpdateProductMedia.class, Builder.class);
    }

    public static final int SKU_FIELD_NUMBER = 1;
    private volatile Object sku_;
    /**
     * <code>string sku = 1;</code>
     * @return The sku.
     */
    public String getSku() {
      Object ref = sku_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sku_ = s;
        return s;
      }
    }
    /**
     * <code>string sku = 1;</code>
     * @return The bytes for sku.
     */
    public com.google.protobuf.ByteString
        getSkuBytes() {
      Object ref = sku_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sku_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FULL_REPLACEMENT_FIELD_NUMBER = 2;
    private boolean fullReplacement_;
    /**
     * <code>bool full_replacement = 2;</code>
     * @return The fullReplacement.
     */
    public boolean getFullReplacement() {
      return fullReplacement_;
    }

    public static final int MEDIA_FIELD_NUMBER = 3;
    private java.util.List<Media> media_;
    /**
     * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
     */
    public java.util.List<Media> getMediaList() {
      return media_;
    }
    /**
     * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
     */
    public java.util.List<? extends MediaOrBuilder>
        getMediaOrBuilderList() {
      return media_;
    }
    /**
     * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
     */
    public int getMediaCount() {
      return media_.size();
    }
    /**
     * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
     */
    public Media getMedia(int index) {
      return media_.get(index);
    }
    /**
     * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
     */
    public MediaOrBuilder getMediaOrBuilder(
        int index) {
      return media_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSkuBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sku_);
      }
      if (fullReplacement_ != false) {
        output.writeBool(2, fullReplacement_);
      }
      for (int i = 0; i < media_.size(); i++) {
        output.writeMessage(3, media_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSkuBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sku_);
      }
      if (fullReplacement_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, fullReplacement_);
      }
      for (int i = 0; i < media_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, media_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UpdateProductMedia)) {
        return super.equals(obj);
      }
      UpdateProductMedia other = (UpdateProductMedia) obj;

      if (!getSku()
          .equals(other.getSku())) return false;
      if (getFullReplacement()
          != other.getFullReplacement()) return false;
      if (!getMediaList()
          .equals(other.getMediaList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SKU_FIELD_NUMBER;
      hash = (53 * hash) + getSku().hashCode();
      hash = (37 * hash) + FULL_REPLACEMENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFullReplacement());
      if (getMediaCount() > 0) {
        hash = (37 * hash) + MEDIA_FIELD_NUMBER;
        hash = (53 * hash) + getMediaList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UpdateProductMedia parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UpdateProductMedia parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UpdateProductMedia parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UpdateProductMedia parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UpdateProductMedia parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UpdateProductMedia parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UpdateProductMedia parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UpdateProductMedia parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UpdateProductMedia parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UpdateProductMedia parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UpdateProductMedia parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UpdateProductMedia parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UpdateProductMedia prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.UpdateProductMedia}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.spice.at.common.dto.dam.grpc.UpdateProductMedia)
        UpdateProductMediaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProductMediaExport.internal_static_ru_spice_at_common_dto_dam_grpc_UpdateProductMedia_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProductMediaExport.internal_static_ru_spice_at_common_dto_dam_grpc_UpdateProductMedia_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UpdateProductMedia.class, Builder.class);
      }

      // Construct using ru.spice.at.common.dto.dam.grpc.ProductMediaExport.UpdateProductMedia.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMediaFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        sku_ = "";

        fullReplacement_ = false;

        if (mediaBuilder_ == null) {
          media_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          mediaBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProductMediaExport.internal_static_ru_spice_at_common_dto_dam_grpc_UpdateProductMedia_descriptor;
      }

      @Override
      public UpdateProductMedia getDefaultInstanceForType() {
        return UpdateProductMedia.getDefaultInstance();
      }

      @Override
      public UpdateProductMedia build() {
        UpdateProductMedia result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UpdateProductMedia buildPartial() {
        UpdateProductMedia result = new UpdateProductMedia(this);
        int from_bitField0_ = bitField0_;
        result.sku_ = sku_;
        result.fullReplacement_ = fullReplacement_;
        if (mediaBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            media_ = java.util.Collections.unmodifiableList(media_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.media_ = media_;
        } else {
          result.media_ = mediaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UpdateProductMedia) {
          return mergeFrom((UpdateProductMedia)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UpdateProductMedia other) {
        if (other == UpdateProductMedia.getDefaultInstance()) return this;
        if (!other.getSku().isEmpty()) {
          sku_ = other.sku_;
          onChanged();
        }
        if (other.getFullReplacement() != false) {
          setFullReplacement(other.getFullReplacement());
        }
        if (mediaBuilder_ == null) {
          if (!other.media_.isEmpty()) {
            if (media_.isEmpty()) {
              media_ = other.media_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMediaIsMutable();
              media_.addAll(other.media_);
            }
            onChanged();
          }
        } else {
          if (!other.media_.isEmpty()) {
            if (mediaBuilder_.isEmpty()) {
              mediaBuilder_.dispose();
              mediaBuilder_ = null;
              media_ = other.media_;
              bitField0_ = (bitField0_ & ~0x00000001);
              mediaBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMediaFieldBuilder() : null;
            } else {
              mediaBuilder_.addAllMessages(other.media_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UpdateProductMedia parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UpdateProductMedia) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object sku_ = "";
      /**
       * <code>string sku = 1;</code>
       * @return The sku.
       */
      public String getSku() {
        Object ref = sku_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sku_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string sku = 1;</code>
       * @return The bytes for sku.
       */
      public com.google.protobuf.ByteString
          getSkuBytes() {
        Object ref = sku_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sku_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sku = 1;</code>
       * @param value The sku to set.
       * @return This builder for chaining.
       */
      public Builder setSku(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sku_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sku = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSku() {
        
        sku_ = getDefaultInstance().getSku();
        onChanged();
        return this;
      }
      /**
       * <code>string sku = 1;</code>
       * @param value The bytes for sku to set.
       * @return This builder for chaining.
       */
      public Builder setSkuBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sku_ = value;
        onChanged();
        return this;
      }

      private boolean fullReplacement_ ;
      /**
       * <code>bool full_replacement = 2;</code>
       * @return The fullReplacement.
       */
      public boolean getFullReplacement() {
        return fullReplacement_;
      }
      /**
       * <code>bool full_replacement = 2;</code>
       * @param value The fullReplacement to set.
       * @return This builder for chaining.
       */
      public Builder setFullReplacement(boolean value) {
        
        fullReplacement_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool full_replacement = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFullReplacement() {
        
        fullReplacement_ = false;
        onChanged();
        return this;
      }

      private java.util.List<Media> media_ =
        java.util.Collections.emptyList();
      private void ensureMediaIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          media_ = new java.util.ArrayList<Media>(media_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Media, Media.Builder, MediaOrBuilder> mediaBuilder_;

      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public java.util.List<Media> getMediaList() {
        if (mediaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(media_);
        } else {
          return mediaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public int getMediaCount() {
        if (mediaBuilder_ == null) {
          return media_.size();
        } else {
          return mediaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Media getMedia(int index) {
        if (mediaBuilder_ == null) {
          return media_.get(index);
        } else {
          return mediaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Builder setMedia(
          int index, Media value) {
        if (mediaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMediaIsMutable();
          media_.set(index, value);
          onChanged();
        } else {
          mediaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Builder setMedia(
          int index, Media.Builder builderForValue) {
        if (mediaBuilder_ == null) {
          ensureMediaIsMutable();
          media_.set(index, builderForValue.build());
          onChanged();
        } else {
          mediaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Builder addMedia(Media value) {
        if (mediaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMediaIsMutable();
          media_.add(value);
          onChanged();
        } else {
          mediaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Builder addMedia(
          int index, Media value) {
        if (mediaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMediaIsMutable();
          media_.add(index, value);
          onChanged();
        } else {
          mediaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Builder addMedia(
          Media.Builder builderForValue) {
        if (mediaBuilder_ == null) {
          ensureMediaIsMutable();
          media_.add(builderForValue.build());
          onChanged();
        } else {
          mediaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Builder addMedia(
          int index, Media.Builder builderForValue) {
        if (mediaBuilder_ == null) {
          ensureMediaIsMutable();
          media_.add(index, builderForValue.build());
          onChanged();
        } else {
          mediaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Builder addAllMedia(
          Iterable<? extends Media> values) {
        if (mediaBuilder_ == null) {
          ensureMediaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, media_);
          onChanged();
        } else {
          mediaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Builder clearMedia() {
        if (mediaBuilder_ == null) {
          media_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          mediaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Builder removeMedia(int index) {
        if (mediaBuilder_ == null) {
          ensureMediaIsMutable();
          media_.remove(index);
          onChanged();
        } else {
          mediaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Media.Builder getMediaBuilder(
          int index) {
        return getMediaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public MediaOrBuilder getMediaOrBuilder(
          int index) {
        if (mediaBuilder_ == null) {
          return media_.get(index);  } else {
          return mediaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public java.util.List<? extends MediaOrBuilder>
           getMediaOrBuilderList() {
        if (mediaBuilder_ != null) {
          return mediaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(media_);
        }
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Media.Builder addMediaBuilder() {
        return getMediaFieldBuilder().addBuilder(
            Media.getDefaultInstance());
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public Media.Builder addMediaBuilder(
          int index) {
        return getMediaFieldBuilder().addBuilder(
            index, Media.getDefaultInstance());
      }
      /**
       * <code>repeated .ru.spice.at.common.dto.dam.grpc.Media media = 3;</code>
       */
      public java.util.List<Media.Builder>
           getMediaBuilderList() {
        return getMediaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Media, Media.Builder, MediaOrBuilder>
          getMediaFieldBuilder() {
        if (mediaBuilder_ == null) {
          mediaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Media, Media.Builder, MediaOrBuilder>(
                  media_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          media_ = null;
        }
        return mediaBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.spice.at.common.dto.dam.grpc.UpdateProductMedia)
    }

    // @@protoc_insertion_point(class_scope:ru.spice.at.common.dto.dam.grpc.UpdateProductMedia)
    private static final UpdateProductMedia DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UpdateProductMedia();
    }

    public static UpdateProductMedia getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateProductMedia>
        PARSER = new com.google.protobuf.AbstractParser<UpdateProductMedia>() {
      @Override
      public UpdateProductMedia parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateProductMedia(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateProductMedia> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UpdateProductMedia> getParserForType() {
      return PARSER;
    }

    @Override
    public UpdateProductMedia getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MediaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.spice.at.common.dto.dam.grpc.Media)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string filename = 1;</code>
     * @return The filename.
     */
    String getFilename();
    /**
     * <code>string filename = 1;</code>
     * @return The bytes for filename.
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>string url = 2;</code>
     * @return The url.
     */
    String getUrl();
    /**
     * <code>string url = 2;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();
  }
  /**
   * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.Media}
   */
  public  static final class Media extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.spice.at.common.dto.dam.grpc.Media)
      MediaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Media.newBuilder() to construct.
    private Media(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Media() {
      filename_ = "";
      url_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Media();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Media(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              filename_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductMediaExport.internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductMediaExport.internal_static_ru_spice_at_common_dto_dam_grpc_Media_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Media.class, Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile Object filename_;
    /**
     * <code>string filename = 1;</code>
     * @return The filename.
     */
    public String getFilename() {
      Object ref = filename_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      }
    }
    /**
     * <code>string filename = 1;</code>
     * @return The bytes for filename.
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 2;
    private volatile Object url_;
    /**
     * <code>string url = 2;</code>
     * @return The url.
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 2;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFilenameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, url_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFilenameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, url_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Media)) {
        return super.equals(obj);
      }
      Media other = (Media) obj;

      if (!getFilename()
          .equals(other.getFilename())) return false;
      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFilename().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Media parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Media parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Media parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Media parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Media parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Media parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Media parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Media parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Media parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Media parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Media parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Media parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Media prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.spice.at.common.dto.dam.grpc.Media}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.spice.at.common.dto.dam.grpc.Media)
        MediaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProductMediaExport.internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProductMediaExport.internal_static_ru_spice_at_common_dto_dam_grpc_Media_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Media.class, Builder.class);
      }

      // Construct using ru.spice.at.common.dto.dam.grpc.ProductMediaExport.Media.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        filename_ = "";

        url_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProductMediaExport.internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor;
      }

      @Override
      public Media getDefaultInstanceForType() {
        return Media.getDefaultInstance();
      }

      @Override
      public Media build() {
        Media result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Media buildPartial() {
        Media result = new Media(this);
        result.filename_ = filename_;
        result.url_ = url_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Media) {
          return mergeFrom((Media)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Media other) {
        if (other == Media.getDefaultInstance()) return this;
        if (!other.getFilename().isEmpty()) {
          filename_ = other.filename_;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Media parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Media) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object filename_ = "";
      /**
       * <code>string filename = 1;</code>
       * @return The filename.
       */
      public String getFilename() {
        Object ref = filename_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string filename = 1;</code>
       * @return The bytes for filename.
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filename = 1;</code>
       * @param value The filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilename(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilename() {
        
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       * @param value The bytes for filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filename_ = value;
        onChanged();
        return this;
      }

      private Object url_ = "";
      /**
       * <code>string url = 2;</code>
       * @return The url.
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string url = 2;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 2;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 2;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.spice.at.common.dto.dam.grpc.Media)
    }

    // @@protoc_insertion_point(class_scope:ru.spice.at.common.dto.dam.grpc.Media)
    private static final Media DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Media();
    }

    public static Media getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Media>
        PARSER = new com.google.protobuf.AbstractParser<Media>() {
      @Override
      public Media parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Media(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Media> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Media> getParserForType() {
      return PARSER;
    }

    @Override
    public Media getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spice_at_common_dto_dam_grpc_UpdateProductMedia_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_spice_at_common_dto_dam_grpc_UpdateProductMedia_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_spice_at_common_dto_dam_grpc_Media_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032product_media_export.proto\022\037ru.spice.a" +
      "t.common.dto.dam.grpc\"r\n\022UpdateProductMe" +
      "dia\022\013\n\003sku\030\001 \001(\t\022\030\n\020full_replacement\030\002 \001" +
      "(\010\0225\n\005media\030\003 \003(\0132&.ru.spice.at.common.d" +
      "to.dam.grpc.Media\"&\n\005Media\022\020\n\010filename\030\001" +
      " \001(\t\022\013\n\003url\030\002 \001(\tB\002Z\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_spice_at_common_dto_dam_grpc_UpdateProductMedia_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_spice_at_common_dto_dam_grpc_UpdateProductMedia_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_spice_at_common_dto_dam_grpc_UpdateProductMedia_descriptor,
        new String[] { "Sku", "FullReplacement", "Media", });
    internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_spice_at_common_dto_dam_grpc_Media_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_spice_at_common_dto_dam_grpc_Media_descriptor,
        new String[] { "Filename", "Url", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
